[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "stowage"
authors = [
	{name = "Keith Gaughan", email = "keith+stowage@gaughan.ie"},
]
readme = "README.rst"
license = {file = "LICENSE"}
classifiers = [
	"License :: OSI Approved :: MIT License",
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"Intended Audience :: End Users/Desktop",
	"Environment :: Console",
]
requires-python = ">=3.5"
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/kgaughan/stowage"

[project.scripts]
stowage = "stowage:main"
